---
- name: Playbook
  hosts: all
  become: yes
  become_user: root
  vars_files:
    - vars/default.yml
  tasks:
    - name: Ping hosts
      ping:

    - name: Add IP Route for c1 and c2
      vars:
        host_names:
          - c1
          - c2
      shell: ip route add 172.16.0.0/24 via 192.168.33.1 dev eth1
      when: "ansible_hostname in host_names"

    - name: Add IP route for s0
      vars:
        host_names:
          - s0
      shell: ip route add 192.168.33.0/24 via 172.16.0.1 dev eth1
      when: ansible_hostname in host_names

    - name: Configure net.ipv4.ip_forward for firewall
      vars:
        host_names:
          - firewall
      shell: sysctl -w net.ipv4.ip_forward=1
      when: ansible_hostname in host_names

    # - name: Add Docker GPG apt Key
    #   apt_key:
    #     url: https://download.docker.com/linux/ubuntu/gpg
    #     state: present

    # - name: Add Docker Repository
    #   apt_repository:
    #     repo: deb https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    #     state: present

    # - name: Update apt and install docker-ce
    #   apt: update_cache=yes name=docker-ce state=latest

    # # Enable using docker command without sudo 
    # - name: Add group "docker"
    #   group:
    #     name: docker
    #     state: present

    # # Enable using docker command without sudo
    # - user:
    #     name: vagrant
    #     groups: docker
    #     append: yes

    # - name: Install Docker Module for Python
    #   pip:
    #     name: docker

    # - name: Pull default Docker image
    #   docker_image:
    #     name: "{{ default_container_image }}"
    #     source: pull

    # # Creates the number of containers defined by the variable create_containers, using values from vars file
    # - name: Create default containers
    #   docker_container:
    #     name: "{{ default_container_name }}{{ item }}"
    #     image: "{{ default_container_image }}"
    #     command: "{{ default_container_command }}"
    #     state: present
    #   with_sequence: count={{ create_containers }}      
