require_relative 'spec'

num_of_machines = Spec::CLUSTER.length

Vagrant.configure(2) do |config|
  config.ssh.insert_key = false 
  
  Spec::CLUSTER.each_with_index do |(hostname, info), index|
    config.vm.define hostname do |node|
      puts "*** VM Index: #{index}, hostname: #{hostname}  info: #{info} ***"
      
      node.vm.box = "bento/ubuntu-16.04"
      node.vm.hostname = "#{hostname.gsub('.', '')}" # VM machine hostname
      node.ssh.host = "127.0.0.1"
      node.ssh.port = "#{info[:fwdports]}"
      node.vm.network "forwarded_port", guest: 22, host: "#{info[:fwdports]}"

      info[:ip].each do |ip|
        node.vm.network "private_network", ip: "#{ip}"
      end

      if index == num_of_machines - 1
        node.vm.provision "ansible" do |ansible|
            # Disable default limit to connect to all the machines
            ansible.limit = "all"
            ansible.verbose = true
            ansible.playbook = "scripts/playbook.yml"
            ansible.extra_vars = { ansible_python_interpreter:"/usr/bin/python3" }
        end
      end
      node.vm.provider "parallels" do |v|
        v.linked_clone = true
        v.name = hostname
        v.memory = "#{info[:mem]}"
        v.cpus = "#{info[:cpus]}"
        v.customize ["set", :id, "--nested-virt", "on"]
      end
    end
  end
end
