require_relative 'spec'

num_of_machines = Spec::CLUSTER.length

Vagrant.configure(2) do |config|
  config.ssh.insert_key = false 
  
  Spec::CLUSTER.each_with_index do |(hostname, info), index|
    config.vm.define hostname do |node|
      puts "*** VM Index: #{index}, hostname: #{hostname}  info: #{info} ***"
      
      node.vm.box = "bento/ubuntu-16.04"
      node.vm.network "private_network", ip: "#{info[:ip]}"
      node.vm.hostname = hostname # VM machine hostname

      # node.vm.network "forwarded_port", guest: 8080, host: 8080
      if index == num_of_machines - 1
        node.vm.provision "ansible" do |ansible|
            # Disable default limit to connect to all the machines
            ansible.limit = "all"
            ansible.verbose = true
            ansible.playbook = "scripts/playbook.yml"
            ansible.extra_vars = { ansible_python_interpreter:"/usr/bin/python3" }
        end
      end
      node.vm.provider "virtualbox" do |v|
        v.linked_clone = true
        # Rename the VM name in virtualbox GUI
        v.name = hostname
        v.memory = "#{info[:mem]}"
        v.cpus = "#{info[:cpus]}"
        v.customize ["modifyvm", :id, "--memory", info[:mem], "--cpus", info[:cpus], "--hwvirtex", "on", "--nested-hw-virt", "on", '--cableconnected1', 'on']
      end
    end
  end
end
