
cluster = {
  "devlinux" => { :ip => "192.168.33.10", :cpus => 2, :mem => 2048 },
}

Vagrant.configure(2) do |config|
  config.ssh.insert_key = false 
  
  cluster.each_with_index do |(hostname, info), index|
    config.vm.define hostname do |node|
      puts "*** VM Index: #{index}, hostname: #{hostname}  info: #{info} ***"
      
      node.vm.box = "bento/ubuntu-16.04"
      node.vm.hostname = hostname # VM machine hostname
      node.ssh.host = "127.0.0.1"
      node.ssh.port = 2322
      node.vm.network "forwarded_port", guest: 22, host: 2322
      node.vm.network "private_network", ip: "#{info[:ip]}"

      # node.vm.network "forwarded_port", guest: 8080, host: 8080
      node.vm.provision "ansible" do |ansible|
          ansible.verbose = true
          ansible.playbook = "scripts/playbook.yml"
          ansible.extra_vars = { ansible_python_interpreter:"/usr/bin/python3" }
      end
      node.vm.provider "parallels" do |v|
        v.linked_clone = true
        v.name = hostname
        v.memory = "#{info[:mem]}"
        v.cpus = "#{info[:cpus]}"
        v.customize ["set", :id, "--nested-virt", "on"]
      end
    end
  end
end
